package com.datastax.driver.core.pipeline;

/**
 * This interface can be used to implement application-specific error handling.
 * When an error is called on a Pipeline's future, the .handle function is
 * called.
 */
public interface PipelineErrorHandler {
    /**
     * @see Pipeline#maximizeInFlightRequests() to see where this function gets
     * executed.
     * @param throwable Generated by FutureCallback<ResultSet>#onFailure.
     */
    void handle(Throwable throwable);
}
